name: Deploy to AWS S3

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "eu-central-1"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} 
  AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_IAM_ROLE }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to S3
      run: |
        aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete --exclude ".vscode/*" --exclude ".github/*" --exclude ".git/*"

    - name: Invalidate CloudFront Distribution
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
